trigger:
    branches:
        include:
        - master
    paths:
        include:
        - NewVideoFunction
        - BuildDataAccess
        - BuildEntities
        - SqlConfig

variables:
  azureServiceConnection: 'Dev(285ec89b-c6b0-46a6-9758-a0bce37bd2da)'
  functioNamespace: 'newvideofunction'
  projectPath: 'NewVideoFunction/NewVideoFunction.csproj'
  buildConfiguration: 'Release'

pool:
  vmImage: 'windows-2022'
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(projectPath)'
  displayName: 'Restore NuGet packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build solution'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
  displayName: 'Publish solution'
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appType: 'functionApp'
    appName: '$(functioNamespace)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
  displayName: Deploy Azure Function
