trigger:
    branches:
        include:
        - master
    paths:
        include:
        - SpaWebApi
        - SpaWebApi.Test
        - BuildDataAccess
        - BuildEntities
        - CollectionDataAccess
        - CollectionEntities
        - VideoDataAccess
        - VideoEntities
        - UserSubscriptionAccess
        - SqlConfig

pool:
  vmImage: 'windows-2022'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'Dev(285ec89b-c6b0-46a6-9758-a0bce37bd2da)'
  projectPath: 'SpaWebApi/SpaWebApi.csproj'
  testProjectPath: 'SpaWebApi.Test/SpaWebApi.Test.csproj'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(projectPath)'
  displayName: 'Restore NuGet packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build solution'
  
- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: 'test'
    projects: '$(testProjectPath)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
  displayName: 'Publish solution'
  
- task: AzureWebApp@1
  displayName: 'deploy to azure'
  inputs:
    azureSubscription: $(azureSubscription)
    appName: 'musicvideobuilder'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'
    deploymentMethod: runFromPackage
    appType: webApp